### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by memoarfaa** [zdimension/SharpBoot#12]
System.NullReferenceException: Object reference not set to an instance of an object.

   at SharpBoot.ISOInfo.<>c.<RefreshISOs>b__37_0() in C:\Users\FekraSupp\Downloads\Compressed\SharpBoot-master\SharpBoot-master\SharpBoot\ISOInfo.cs:line 156

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart()

line 156 "Settings.Default.AppDBVersion = int.Parse(root.Attribute("version").Value);"

your host is down

**Comment by zdimension** [comment]
Yes, I'm working on that. It'll be up soon.

**Comment by memoarfaa** [comment]
stile not working new exception is
"The 'link' start tag on line 31 position 6 does not match the end tag of 'head'. Line 65, position 5."

**Comment by zdimension** [comment]
fixed in dev, will be in v5
